### ISSUE TITLE
SpringCloud使用Prometheus监控(基于Eureka)

### ISSUE THREAD

**Issue by dalaoyang** [dalaoyang/dalaoyang-message#100]
https://www.dalaoyang.cn/article/102 

 本网站是dalaoyang-大老杨的技术分享博客。内容涵盖Java、Linux、Spring Boot、Spring Cloud、微服务架构、踩坑历程。

**Comment by andyslin** [comment]
请教一下，如果eureka-server有自己的context-path，在prometheus中需要怎么配置？

**Comment by dalaoyang** [comment]
@andyslin 在prometheus的metrics_path属性中配置，比如context-path为aaa那么配置为： metrics_path: '/aaa/actuator/prometheus'

**Comment by andyslin** [comment]
> @dalaoyang
> @andyslin 在prometheus的metrics_path属性中配置，比如context-path为aaa那么配置为： metrics_path: '/aaa/actuator/prometheus'

我试过了，不行。在获取datacenter的时候，就直接报404错误了，我还尝试了直接配置 datacenter为default也不行。
另外一个，如果注册在eureka-server中的微服务也有context-path，在prometheus中怎么配置？

**Comment by dalaoyang** [comment]
@andyslin 我有空试一下吧

**Comment by andyslin** [comment]
> @dalaoyang
> @andyslin 我有空试一下吧

谢谢~~~

对于第一个问题：我使用了nginx临时解决了：
```nginx
  location ^~ / {
            proxy_pass http://host/context-path/;
            proxy_set_header  Host $host;
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
  }
```

对于第2个问题，使用eureka.instance.metadata-map.configPath和relabel可以解决：
```yml
    relabel_configs:
      - source_labels: ['__meta_consul_metadata_configPath']
        target_label: __metrics_path__
        action: replace
        replacement: "$1/actuator/prometheus"
```
